# Generated by Django 5.1.3 on 2024-12-04 12:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Authors',
            fields=[
                ('author_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('author_name', models.CharField(max_length=355)),
                ('bio', models.TextField(max_length=800)),
                ('authorimage', models.ImageField(upload_to='authors/')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('nationality', models.CharField(max_length=200)),
                ('website', models.URLField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('movie_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('language', models.CharField(max_length=255)),
                ('duration', models.DecimalField(decimal_places=2, max_digits=10)),
                ('director', models.CharField(max_length=255)),
                ('maleactor', models.CharField(max_length=255)),
                ('femaleactor', models.CharField(max_length=255)),
                ('music', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('movieimage', models.ImageField(upload_to='movies/%Y/%m/%d/')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('book_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('book_name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('language', models.CharField(max_length=255)),
                ('publish_date', models.DateField(blank=True, null=True)),
                ('publisher_name', models.CharField(max_length=255)),
                ('total_pages', models.IntegerField()),
                ('books_available', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('isbn', models.CharField(max_length=13, unique=True)),
                ('book_image', models.ImageField(upload_to='book_images/')),
                ('author_uuid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='books', to='bookeasy.authors')),
            ],
        ),
    ]
