# Generated by Django 5.1.3 on 2024-12-04 14:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookeasy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cart_it',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
