# Generated by Django 5.1.3 on 2024-12-07 10:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookeasy', '0004_userprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_no', models.CharField(blank=True, editable=False, max_length=15, unique=True)),
                ('product_name', models.TextField(editable=False)),
                ('product_image', models.ImageField(blank=True, editable=False, null=True, upload_to='order_product_images/')),
                ('product_quantity', models.PositiveIntegerField(default=1, editable=False)),
                ('total_amount', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('order_time', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], default='Pending', max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
